// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var novaPontuacao = 20;

var boasVindas = "Oi!";

var pontos = 10;

exports.boasVindas = boasVindas;
exports.pontos = pontos;
exports.novaPontuacao = novaPontuacao;
/* No side effect */
